###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: python


###
### Add services
###
services:
  - docker


###
### Build Matrix definition
###
env:
  global:
    - IMAGE=devilbox/apache-2.4
    # travis encrypt DOCKER_USERNAME=user
    # travis encrypt DOCKER_PASSWORD=pass
    # Must be regenerated when repository name/owner changes
    - secure: "kgorRtrelL9/3lmSu6SD2gs/rN8zBql4tpEg/HAmRysXN33UHwDQD8npdbu8bDPqcG5yAMOM3Wod18iUk149QLd5Ma5fAKk+z56j+Ty7yDDN2AzeyZR5XXsl+wToyR45Fdf4zQYwmcovJ7qJil7mmhfT/k+jRyNlHrjtfzpPQVttTyDiyDCJ0mup6B1VQuEnkpzg7LwjI2G01+lEFDxgSa6z/yC6RFgCJZxoKm9pv/uTTCMkXnNWuS1WxGOTuMeHZMKEQr5lOaqG6u78chYrH3lW+ED3Fh7KOnhz8moBmxcPfqNXlWXReUWa7+37E8iQTz1d6UpRyvMtPcBQR8x2BJvgVS3ZclKVrVnFuE1ny5A8n4D8Va8+L3R+sDigEbWMEoubVgzmzNWfUjWowzFZir1Jyn3LG9yP2pI+i0iqNO5ftYVNl8NpR6Nk0p7RsA2onbvSDkSy5AP+80YBLQ5VRKQd/Z+YSuG3xDV9vowF21+Val8VnRLph6OH7fckkWHkxi6EnimI3h548O6urR3uow6izGwiDXf5zHOz3tGSErfx6W3r5VWnRNq05M++IFQjVLYpx7M1esN/cemJTiKzDM/7L1VNgqfjp5dvdbCRnkQquUF8reVsFIqc3Qgl3lxF76cnn5HSR3i9O7t+dgKqivIjDjOthzqOQg+crzgpzbA="
    - secure: "OXlFtXuk4j29jM72TJRmhDYQVjxnwEcQHXhVDcymduPC5qMJtIUEqFixMT45PBQE/lDvr3CFT1lCnGZ5zU+48OJ/GqUul2IoeXgvifVNNIXxM6IEvoDhANIxm2mOzZvR7Pw6zw1Ti1OUyWSLecHKwoN1SrkeyaWmdNstalqJhoIdHLtNz0lAspGjxTVrLLU3NFeqaZI3NmI1kpFEg7b7opx3LCN/d8bR0iYbKuHjxp5+2y5jpJcGEb96BpQ0M7iLx/h1hdoOfPfnDC++AQmjo/6UJUrJw67qhW/ua7ZfyN87gaPnfgyb9YPhQgKB70GuwDbd7zvBuA1NyzcO2anrLCwZ+CUrPRtmEFDsJR0+s1LkvdwZMz4R058QjiXlzxfD7Sim+JNWu5/2c11HkYmYXX2O1bNYLMnDVjlqx6EWT5JLcxQW0mrh77MzehOAh7n6M8LOdcK+WCuQSK9Z96FkSPHq0peImCHRNB7KSdMKA67Js7IX/s8LiUgvtl7WtK6CKVuN1xbu2ZxUxUGKLKFqCP5BioB6PxDCWreTeXPlAjA7jtOUFhmij6+iVFbANBboyrcuJi+BVnPgEPQLi435Pit7uo1hGe/59lLTbFi/6TpMTod8GY1RoyPhJmwRJzQsETsE+L/Kql9CxRSigAsI8pTW6fCDTyl9RUhRE0ZhwCE="
  matrix:
    - TEST=0
    - TEST=1


###
### Stage definitions
###
stages:
  - test
  - deploy


###
### Global for all stages
###
install:
  # Get newer docker version
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
  - docker version
script:
  - .ci/start-ci.sh "${TEST}" "${IMAGE}"


###
### Job definitions
###
jobs:
  include:
    # Final deploy stage
    - stage: deploy
      env: TEST=
      before_script:
        - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
            if [ -n "${TRAVIS_TAG}" ]; then
              docker build --no-cache=true -t "${IMAGE}:${TRAVIS_TAG}" . &&
              docker images;
            elif [ "${TRAVIS_BRANCH}" == "master" ]; then
              docker build --no-cache=true -t "${IMAGE}:latest" . &&
              docker images;
            elif [[ ${TRAVIS_BRANCH} =~ ^(release[/-][.0-9]+)$ ]]; then
              docker build --no-cache=true -t "${IMAGE}:${TRAVIS_BRANCH}" . &&
              docker images;
            else
              echo "Skipping branch ${TRAVIS_BRANCH}";
            fi
          fi
      script:
        # Push to docker hub on success
        - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
            if [ -n "${TRAVIS_TAG}" ]; then
              docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" &&
              echo "Pushing ${IMAGE}:${TRAVIS_TAG}" &&
              docker push "${IMAGE}:${TRAVIS_TAG}" &&
              docker tag "${IMAGE}:${TRAVIS_TAG}" "${IMAGE}:latest" &&
              echo "Pushing ${IMAGE}:latest" &&
              docker push "${IMAGE}:latest";
            elif [ "${TRAVIS_BRANCH}" == "master" ]; then
              docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" &&
              echo "Pushing ${IMAGE}:latest" &&
              docker push "${IMAGE}:latest";
            elif [[ ${TRAVIS_BRANCH} =~ ^(release[/-][.0-9]+)$ ]]; then
              docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" &&
              echo "Pushing ${IMAGE}:${TRAVIS_BRANCH}" &&
              docker push "${IMAGE}:${TRAVIS_BRANCH}";
            else
              echo "Skipping branch ${TRAVIS_BRANCH}";
            fi
          fi
