###
### Enable sudo (required for docker service)
###
sudo: required


###
### Add services
###
services:
  - docker


###
### Global variables
###
env:
  - S1=0
  - S1=1


###
### Disable auto-started daemons
###
before_script:

  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop || true
  - sudo /etc/init.d/postgresql stop || true
  - sudo service mysql stop || true
  - sudo service postgresql stop || true


###
### Test
###
script:
  - .ci/start-ci.sh "${S1}"
