language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t cytopia/apache-2.4 .
  - docker run -d -p 127.0.0.1:80:80 --name apache-2.4 cytopia/apache-2.4

#before_script:
#  - pip install -r requirements.txt
#  - pip install mock
#  - pip install requests
#  - pip install feedparser

script:
  - docker ps | grep -q apache-2.4
  #- python tests.py
